added some '>&2'
git-svn-id: http://svn.linux-vserver.org/svn/util-vserver/trunk@1105 94cd875c-1c1d-0410-91d2-eb244daf1a30

diff --git a/util-vserver/scripts/chcontext b/util-vserver/scripts/chcontext
--- a/util-vserver/scripts/chcontext
+++ b/util-vserver/scripts/chcontext
@@ -18,7 +18,7 @@
 
 : ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo "Can not find util-vserver installation; aborting..."
+    echo "Can not find util-vserver installation; aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
@@ -134,7 +134,7 @@ while true; do
 	--secure)	OPT_SECURE=1;;
 	--silent)	OPT_SILENT=1;;
 	--)		shift; break;;
-	*)		echo $"chcontext: internal error; arg=='$1'"; exit 1;;
+	*)		echo $"chcontext: internal error; arg=='$1'" >&2; exit 1;;
     esac
     shift
 done
@@ -146,13 +146,13 @@ trap "cleanup" EXIT
 xid=$($_VCONTEXT --create ${OPT_SILENT:+--silent} ${OPT_CTX:+--xid "$OPT_CTX"} -- $_CTX_KEEP_ALIVE --socket "$tmpdir"/socket --timeout 60)
 rc=$?
 test "$rc" -ne 255 ||
-    echo $"chcontext: Failed to create the context; aborting..."
+    echo $"chcontext: Failed to create the context; aborting..." >&2
     exit 1
 }
 
 test "$rc" -ne 254 || xid=$OPT_CTX
 test "$xid" || {
-    echo $"chcontext: Failed to determine context xid; aborting..."
+    echo $"chcontext: Failed to determine context xid; aborting..." >&2
     exit 1
 }
 
diff --git a/util-vserver/scripts/vserver b/util-vserver/scripts/vserver
--- a/util-vserver/scripts/vserver
+++ b/util-vserver/scripts/vserver
@@ -20,7 +20,7 @@
 
 : ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo "Can not find util-vserver installation; aborting..."
+    echo "Can not find util-vserver installation; aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
@@ -132,7 +132,7 @@ while true; do
 	--silent) 	OPTION_SILENT=$1;;
 	----nonamespace)OPTION_NONAMESPACE=$1;;
 	--)	   	shift; break;;
-	*)	   	echo $"vserver: internal error; arg=='$1'"; exit 1;;
+	*)	   	echo $"vserver: internal error; arg=='$1'" >&2; exit 1;;
     esac
     shift
 done
@@ -162,7 +162,7 @@ if test "$allow_legacy"; then
     test -d "$VSERVER_DIR" -o ! -e "$CONFDIR/$vserver.conf" || do_legacy=1
 
     test -z "$do_legacy" || {
-	echo $"WARNING: can not find configuration, assuming legacy method"
+	echo $"WARNING: can not find configuration, assuming legacy method" >&2
 	exec "$_VSERVER_LEGACY" "$@"
     }
 fi
@@ -170,7 +170,7 @@ fi
 test -d "$VSERVER_DIR" || {
     echo "Can not find vserver-setup"
     exit 1
-}
+} >&2
 
 if test -e "$VSERVER_DIR"/name; then
     read VSERVER_NAME <"$VSERVER_DIR"/name
@@ -245,7 +245,7 @@ case "$2" in
 	fi
 	;;
     *)
-	echo $"Usage: $0 {start|stop|suexec|restart|condrestart|exec|enter|chkconfig|running|status}"
+	echo $"Usage: $0 {start|stop|suexec|restart|condrestart|exec|enter|chkconfig|running|status}" >&2
 	exit 2
 	;;
 esac
diff --git a/util-vserver/scripts/vserver-build b/util-vserver/scripts/vserver-build
--- a/util-vserver/scripts/vserver-build
+++ b/util-vserver/scripts/vserver-build
@@ -18,7 +18,7 @@
 
 : ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo "Can not find util-vserver installation; aborting..."
+    echo "Can not find util-vserver installation; aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
@@ -102,7 +102,7 @@ while true; do
 	--)	   shift; break;;
 	*)
 	    { setup_setOption2 "$1" "$2" && shift; } || \
-	    { echo $"vserver-build: internal error."; exit 1; }
+	    { echo $"vserver-build: internal error."; exit 1; } >&2
 	    ;;
     esac
     shift
@@ -111,7 +111,7 @@ done
 test "$VSERVER_NAME" || {
     echo $"Name of vserver not specified"
     exit 1
-}
+} >&2
 
 setup_setDefaults "$VSERVER_NAME"
 
diff --git a/util-vserver/scripts/vserver-copy b/util-vserver/scripts/vserver-copy
--- a/util-vserver/scripts/vserver-copy
+++ b/util-vserver/scripts/vserver-copy
@@ -38,7 +38,7 @@
 
 : ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo "Can not find util-vserver installation; aborting..."
+    echo "Can not find util-vserver installation; aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
