This commit was manufactured by cvs2svn to create tag 'version_0_23_95'.
git-svn-id: http://svn.linux-vserver.org/svn/util-vserver/tags/version_0_23_95@317 94cd875c-1c1d-0410-91d2-eb244daf1a30

diff --git a/util-vserver/scripts/distrib-info b/util-vserver/scripts/distrib-info
--- a/util-vserver/scripts/distrib-info
+++ b/util-vserver/scripts/distrib-info
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
 # based on distrib-info by Jacques Gelinas
@@ -25,7 +25,12 @@
 # distrib-info vserver1 pkgversion
 # If vserver1 is a redhat system, it executes
 # rpm -qa --queryformat "%{name}=%{version}-%{release}
-USR_LIB_VSERVER=$(dirname $0)
+: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
+test -e "$UTIL_VSERVER_VARS" || {
+    echo "Can not find util-vserver installation; aborting..."
+    exit 1
+}
+. "$UTIL_VSERVER_VARS"
 
 if [ "$1" = "" ] ; then
 	echo distrib-info vserver-name command [ args ... ] >&2
@@ -40,10 +45,10 @@ if [ "$1" = "/" ] ; then
 	CHROOTCMD=
 elif [ -d "$1" ] ; then
 	DISTDIR=$1
-	CHROOTCMD="/usr/sbin/chroot $DISTDIR"
+	CHROOTCMD="$SBINDIR/chroot $DISTDIR"
 else
 	DISTDIR=/vservers/$1
-	CHROOTCMD="/usr/sbin/chroot $DISTDIR"
+	CHROOTCMD="$SBINDIR/chroot $DISTDIR"
 fi
 KEY=$2
 shift
@@ -57,7 +62,7 @@ if [ -f $DIRDIR/etc/redhat-release -o -f $DISTDIR/etc/mandrake-release ] ; then
 		# We remove /etc and /var/log to make sure no special file
 		# there will be unified
 		$CHROOTCMD /bin/rpm -ql --dump $* \
-			| $USR_LIB_VSERVER/parserpmdump /etc/
+			| $PKGLIBDIR/parserpmdump /etc/
 		;;
 	dumpfiles)
 		$CHROOTCMD /bin/rpm -ql $*
diff --git a/util-vserver/scripts/vserver-copy b/util-vserver/scripts/vserver-copy
--- a/util-vserver/scripts/vserver-copy
+++ b/util-vserver/scripts/vserver-copy
@@ -36,6 +36,13 @@
 #   used so that if/when you reboot the source roothost you don't have the
 #   same vserver and IP address running on two machines.
 
+: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
+test -e "$UTIL_VSERVER_VARS" || {
+    echo "Can not find util-vserver installation; aborting..."
+    exit 1
+}
+. "$UTIL_VSERVER_VARS"
+
 VERSION="0.4"
 umask 022
 me=${0##*/}
@@ -271,7 +278,7 @@ if [ -n "$ip" ] && \
 fi
 
 # This works both locally and remote
-if ($shcmd $dhost /usr/sbin/vserver $newname running | grep 'is running'); then
+if ($shcmd $dhost $SBINDIR/vserver $newname running | grep 'is running'); then
 	warn "destination vserver \"$newname\" is running" 
 	error 1 "Cannot copy over a running vserver"
 fi
@@ -283,7 +290,7 @@ info "Attempting to copy $vserver to $dhost$colon$newname"
 
 if $stopstart; then
 	info "Stopping virtual server \"$vserver\" on localhost"
-	/usr/sbin/vserver $vserver stop
+	$SBINDIR/vserver $vserver stop
 fi
 
 info "Syncing directories"
@@ -358,8 +365,8 @@ fi
 
 if $stopstart; then
 	info "Starting virtual server \"$vserver\" on $dhost"
-	$shcmd $dhost /usr/sbin/vserver $vserver start
-	if ($shcmd $dhost /usr/sbin/vserver $vserver running | \
+	$shcmd $dhost $SBINDIR/vserver $vserver start
+	if ($shcmd $dhost $SBINDIR/vserver $vserver running | \
 	grep 'not running'); then
 		error 1 "Virtual server \"$vserver\" failed to start on $dhost"
 	fi
