This commit was manufactured by cvs2svn to create tag 'version_0_23_94'.
git-svn-id: http://svn.linux-vserver.org/svn/util-vserver/tags/version_0_23_94@310 94cd875c-1c1d-0410-91d2-eb244daf1a30

diff --git a/util-vserver/scripts/rootshell b/util-vserver/scripts/rootshell
--- a/util-vserver/scripts/rootshell
+++ b/util-vserver/scripts/rootshell
@@ -16,11 +16,16 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 
+: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
+test -e "$UTIL_VSERVER_VARS" || {
+    echo "Can not find util-vserver installation; aborting..."
+    exit 1
+}
+. "$UTIL_VSERVER_VARS"
 
-echo $* >/tmp/log
 OPTIONS=$@
 if [ "$OPTIONS" = "" ] ; then
 	OPTIONS=--login
 fi
-exec /usr/sbin/chbind --silent --ip 0.0.0.0 /bin/bash $OPTIONS
+exec $SBINDIR/chbind --silent --ip 0.0.0.0 /bin/bash $OPTIONS
 
diff --git a/util-vserver/scripts/vsysvwrapper b/util-vserver/scripts/vsysvwrapper
--- a/util-vserver/scripts/vsysvwrapper
+++ b/util-vserver/scripts/vsysvwrapper
@@ -18,7 +18,13 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 
 # Helper script for all the v_xxx scripts
-USR_SBIN=/usr/sbin
+: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
+test -e "$UTIL_VSERVER_VARS" || {
+    echo "Can not find util-vserver installation; aborting..."
+    exit 1
+}
+. "$UTIL_VSERVER_VARS"
+
 if [ $# = 0 ] ; then
 	echo vsysvwrapper service_name >&2
 else
@@ -33,8 +39,8 @@ else
 	do
 		IPOPT="$IPOPT --ip $oneip"
 	done
-	echo exec $USR_SBIN/chbind $IPOPT /etc/init.d/$SERVICE $*
-	exec $USR_SBIN/chbind $IPOPT /etc/init.d/$SERVICE $*
+	echo exec $SBINDIR/chbind $IPOPT /etc/init.d/$SERVICE $*
+	exec $SBINDIR/chbind $IPOPT /etc/init.d/$SERVICE $*
 fi
 
 
