give more verbose error-messages
git-svn-id: http://svn.linux-vserver.org/svn/util-vserver/trunk@1440 94cd875c-1c1d-0410-91d2-eb244daf1a30

diff --git a/util-vserver/scripts/vprocunhide b/util-vserver/scripts/vprocunhide
--- a/util-vserver/scripts/vprocunhide
+++ b/util-vserver/scripts/vprocunhide
@@ -18,7 +18,7 @@
 
 : ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo $"Can not find util-vserver installation; aborting...">&2
+    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
