Use correct path for vserver-wrapper

diff --git a/sysv/vservers-default b/sysv/vservers-default
--- a/sysv/vservers-default
+++ b/sysv/vservers-default
@@ -37,6 +37,13 @@ if test -r /etc/default/vservers-default; then
     . /etc/default/vservers-default
 fi
 
+: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
+test -e "$UTIL_VSERVER_VARS" || {
+    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
+    exit 1
+}
+. "$UTIL_VSERVER_VARS"
+
 export MARK NUMPARALLEL LOCKFILE
-exec /usr/lib/util-vserver/vserver-wrapper "$@"
+exec "$_VSERVER_WRAPPER" "$@"
 
