Make vrpm and vapt-get use vsomething. Fix external package management so that the process is executed in the guest's network context, in case scriptlets restart daemons.
git-svn-id: http://svn.linux-vserver.org/svn/util-vserver/trunk@2303 94cd875c-1c1d-0410-91d2-eb244daf1a30

diff --git a/scripts/vapt-get b/scripts/vapt-get
--- a/scripts/vapt-get
+++ b/scripts/vapt-get
@@ -31,7 +31,7 @@ function showHelp()
 $"Usage: $0 <vserver-name>* [--all] -- <params>+
 
 Report bugs to <$PACKAGE_BUGREPORT>."
-    exit $1
+    exit 0
 }
 
 function showVersion()
@@ -40,60 +40,35 @@ function showVersion()
 $"vapt-get $PACKAGE_VERSION -- apt-get for vservers
 This program is part of $PACKAGE_STRING
 
-Copyright (C) 2003 Enrico Scholz
+Copyright (C) 2006 Enrico Scholz
 This program is free software; you may redistribute it under the terms of
 the GNU General Public License.  This program has absolutely no warranty."
-    exit $1
+    exit 0
 }
 
-is_quiet=
-declare -a vservers=()
+tmp=$(getopt -o +q --long help,version,debug,quiet,all -n "$0" -- "$@") || exit 1
+eval set -- "$tmp"
 
-while test "$#" -ge 1; do
+declare -a send_through vsomething_opts
+
+while true; do
     case "$1" in
-	--)		shift; break;;
-	--help)		showHelp 0;;
-	--quiet|-q)	is_quiet=1 ;;
-	--all)
-	    getAllVservers tmp
-	    vservers=( "${vservers[@]}" "${tmp[@]}" )
-	    ;;
-	--version)
-	    showVersion 0;;
-	*)  vservers=( "${vservers[@]}" "$1" )
-     esac
-     shift
+	(--help)    	showHelp $0 ;;
+	(--version) 	showVersion ;;
+	(--debug)	send_through=( "${send_through[@]}" "$1" ); set -x;;
+	(--quiet|-q)	send_through=( "${send_through[@]}" "$1" );;
+	(--all)         vsomething_opts=( "${vsomething_opts[@]}" "$1" );;
+	(--)		shift; break;;
+	(*)	   	echo $"vapt-get: internal error; arg=='$1'" >&2; exit 1;;
+    esac
+    shift
 done
 
-test "$#" -ge 1 || showHelp 1 >&2
-test "${#vservers[@]}" -ne 1 || is_quiet=1
+VSOMETHING_TITLE=vapt-get
+VSOMETHING_WORKER=$_VAPT_GET_WORKER
+VSOMETHING_PKGMGMT=1
 
-cnt=0
-res=255
-for i in "${vservers[@]}"; do
-    cnt=$[ cnt + 1 ]
+export VSOMETHING_TITLE VSOMETHING_WORKER VSOMETHING_PKGMGMT
 
-    test -n "$is_quiet" || {
-	colorize bold echo -n "vaptget: operating on vserver "
-	colorize bold colorize emph echo "$i"
-	xtermTitle "vaptget: operating on vserver '$i'  [$cnt/${#vservers[@]}]"
-    }
-    
-    if pkgmgmt.isInternal "$i"; then
-	$_VSERVER "$i" exec apt-get "$@"
-    else
-	callInNamespace "$i" \
-	    "$_VNAMESPACE" --new -- "$_VAPT_GET_WORKER" "$i" "$@"
-    fi
-    res=$?
-
-    test $res -eq 0 -o -n "$is_quiet" || {
-	colorize error echo -n $"vapt-get failed on vserver '$i' with errorcode $res"
-	echo
-    }
-	
-    test -n "$is_quiet" || echo
-done
-
-test "$cnt" -ge 0 || echo "No vservers specified" >&2
-exit $res
+test ${#vsomething_opts[@]} -eq 0 || vsomething_opts=( "${vsomething_opts[@]}" -- )
+exec $_VSOMETHING "${send_through[@]}" apt-get "${vsomething_opts[@]}" "$@"
diff --git a/scripts/vrpm b/scripts/vrpm
--- a/scripts/vrpm
+++ b/scripts/vrpm
@@ -24,14 +24,14 @@ test -e "$UTIL_VSERVER_VARS" || {
 . "$UTIL_VSERVER_VARS"
 . "$_LIB_FUNCTIONS"
 
+
 function showHelp()
 {
     echo \
-$"Usage: $0 <vserver-name>* [--all] [--quiet|-q] [--help] [--version] [--unify] -- <rpm-params>+
+$"Usage: $0 <vserver-name>* [--all] -- <params>+
 
 Report bugs to <$PACKAGE_BUGREPORT>."
-
-    exit $1
+    exit 0
 }
 
 function showVersion()
@@ -40,71 +40,35 @@ function showVersion()
 $"vrpm $PACKAGE_VERSION -- rpm for vservers
 This program is part of $PACKAGE_STRING
 
-Copyright (C) 2003 Enrico Scholz
+Copyright (C) 2006 Enrico Scholz
 This program is free software; you may redistribute it under the terms of
 the GNU General Public License.  This program has absolutely no warranty."
-    
-    exit $1
+    exit 0
 }
 
-do_unify=
-is_quiet=
-declare -a vservers=()
+tmp=$(getopt -o +q --long help,version,debug,quiet,all -n "$0" -- "$@") || exit 1
+eval set -- "$tmp"
 
-while test "$#" -ge 1; do
+declare -a send_through vsomething_opts
+
+while true; do
     case "$1" in
-	--quiet|-q)
-	    is_quiet=1
-	    ;;
-	--all)
-	    getAllVservers tmp
-	    vservers=( "${vservers[@]}" "${tmp[@]}" )
-	    ;;
-	--unify)
-	    do_unify=1
-	    ;;
-	--)
-	    shift; break;;
-	--help)
-	    showHelp 0;;
-	--version)
-	    showVersion 0;;
-	*)  vservers=( "${vservers[@]}" "$1" )
-     esac
-     shift
+	(--help)    	showHelp $0 ;;
+	(--version) 	showVersion ;;
+	(--debug)	send_through=( "${send_through[@]}" "$1" ); set -x;;
+	(--quiet|-q)	send_through=( "${send_through[@]}" "$1" );;
+	(--all)         vsomething_opts=( "${vsomething_opts[@]}" "$1" );;
+	(--)		shift; break;;
+	(*)	   	echo $"vrpm: internal error; arg=='$1'" >&2; exit 1;;
+    esac
+    shift
 done
 
-test "$#" -ge 1 || showHelp 1 >&2
-test "${#vservers[@]}" -ne 1 || is_quiet=1
+VSOMETHING_TITLE=vrpm
+VSOMETHING_WORKER=$_VRPM_WORKER
+VSOMETHING_PKGMGMT=1
 
-cnt=0
-res=255
+export VSOMETHING_TITLE VSOMETHING_WORKER VSOMETHING_PKGMGMT
 
-for i in "${vservers[@]}"; do
-    cnt=$[ cnt + 1 ]
-
-    test -n "$is_quiet" || {
-	colorize bold echo -n "vrpm: operating on vserver "
-	colorize bold colorize emph echo "$i"
-	xtermTitle "vrpm: operating on vserver '$i'  [$cnt/${#vservers[@]}]"
-    }
-
-    if pkgmgmt.isInternal "$i"; then
-	$_VSERVER "$i" exec rpm "$@"
-    else
-	callInNamespace "$i" \
-	    "$_VNAMESPACE" --new -- "$_VRPM_WORKER" "$i" "$@"
-    fi
-    res=$?
-
-    test $res -eq 0 -o "$is_quiet" || {
-	colorize error echo -n $"vrpm failed on vserver '$i' with errorcode $res"
-	echo
-    }
-
-    test -n "$is_quiet" || echo
-done
-
-test -z "$do_unify" || echo "unify currently unsupported" >&2
-test "$cnt" -ge 0   || echo "No vservers specified" >&2
-exit $res
+test ${#vsomething_opts[@]} -eq 0 || vsomething_opts=( "${vsomething_opts[@]}" -- )
+exec $_VSOMETHING "${send_through[@]}" rpm "${vsomething_opts[@]}" "$@"
